---
# tasks file for namespace

# Namespace
- name: Namespaces template
  template:
    src=templates/namespace.j2
    dest={{dest_path}}/{{item.name}}-namespace.json
  with_items: "{{ namespaces }}"
  when: item != None
  changed_when: False
  tags: [namespaces, template]

- name: Apply Namespaces
  command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-namespace.json
  with_items: "{{ namespaces }}"
  when: item != None and not ansible_check_mode
  tags: [namespaces]