---
# defaults file for serviceaccount

role_name: "{{role_path|basename}}"
resource_type: "{{role_name}}"
resources: "{{ namespace.services|default([])|selectattr('roleBinding', 'defined')|list + namespace.daemonsets|default([])|selectattr('roleBinding', 'defined')|list }}"
