- name: Kubernetes Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  strategy: debug
  no_log: False 
  vars:
    dest_path: /docker
    sidecars: []

  pre_tasks:
    - name: merge yaml files
      shell: yamlreader $(find {{dir}} -name "*.yml" -type f) > /dev/shm/services.yml
      args:
        executable: /bin/bash
      when: services is undefined
      tags: [always]

    - name: include vars
      include_vars:
        file: '/dev/shm/services.yml'
      when: services is undefined
      tags: [always]

  roles:
    - namespace
    - networkpolicy
    - persistentvolume
    - limit
    - configmap
    - secret
    - podpreset
    - daemonset
    - service
    - deployment
    - statefulset
    - hpa
    - endpoint

