- name: Kubernetes Playbook
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    enable_delete: true
    max_delete: 10 #todo
    dest_path: "{{ansible_env.PWD}}/../"
  pre_tasks:
    - name: merge yaml files
      shell: 'yamlreader $(find {{inventory_dir}} -name "*.yml" -type f ! -path "*/disabled/*") > {{dest_path}}/services.yml'
      args:
        executable: /bin/bash
      when: namespaces is undefined
      tags: [always]

    - name: read merged file
      include_vars:
        file: '{{dest_path}}/services.yml'
      when: namespaces is undefined
      tags: [always]
  tasks:
    - include_role: name=priorityclass
    - include: included.yml namespace="{{ {'name':namespace_name}|combine(namespaces[namespace_name]) }}"
      with_items: "{{namespaces|list}}"
      loop_control:
        loop_var: namespace_name
      tags: [always]
