- name: Kubernetes Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  strategy: debug
  no_log: False 
  vars:
    service_template: "service.j2"
    service_canary_template: "service-canary.j2"
    endpoints_template: "endpoints.j2"
    secret_template: "secret.j2"
    daemonset_template: "daemonset.j2"
    deployment_template: "deployment.j2"
    hpa_template: "hpa.j2"
    configmap_template: "configmap.j2"
    limits_template: "limits.j2"
    pv_template: "pv.j2"
    pvc_template: "pvc.j2"
    namespace_template: "namespace.j2"
    networkpolicy_template: "networkpolicy.j2"
    podpresets_template: "podpresets.j2"
    dest_path: /docker
    services: []
    daemonsets: []
    deployments: []
    sidecars: []
    configmaps: []
    persistentVolumes: []
    persistentVolumeClaims: []
    limits: []
    secrets: []
    namespaces: []
    networkpolicies: []
    podpresets: []

  tasks:

    # Namespace
    - name: Namespaces template
      template: src={{namespace_template}} dest={{dest_path}}/{{item.name}}-namespace.json
      with_items: "{{ namespaces }}"
      when: item != None
      changed_when: False
      tags: [namespaces, template]
    
    - name: Apply Namespaces
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-namespace.json 
      with_items: "{{ namespaces }}"
      when: item != None and not ansible_check_mode
      tags: [namespaces]
      
    # Persistent Volumes
    - name: Persistent Volume template
      template: src={{pv_template}} dest={{dest_path}}/{{item.name}}-pv.json
      with_items: "{{ persistentVolumes }}"
      when: item != None
      changed_when: False
      tags: [pv, template]
    
    - name: Apply Persistent Volumes
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-pv.json 
      with_items: "{{ persistentVolumes }}"
      when: item != None and not ansible_check_mode
      tags: [pv]

    # Persistent Volume Claims
    - name: Persistent Volume Claim template
      template: src={{pvc_template}} dest={{dest_path}}/{{item.name}}-pvc.json
      with_items: "{{ persistentVolumeClaims }}"
      when: item != None
      changed_when: False
      tags: [pvc, template]

    - name: Apply Persistent Volume Claims
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-pvc.json
      with_items: "{{ persistentVolumeClaims }}"
      when: item != None and not ansible_check_mode
      ignore_errors: yes
      tags: [pvc]

    # Limits
    - name: limits template
      template: src={{limits_template}} dest={{dest_path}}/limits.json
      with_items: "{{ limits }}"
      when: item != None
      changed_when: False
      tags: [limits, template]

    - name: apply limits
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/limits.json
      with_items: "{{ limits }}"
      when: item != None and not ansible_check_mode
      tags: [limits]

    # ConfigMap

    - name: configmap template
      template: src={{configmap_template}} dest={{dest_path}}/{{item.name}}-configmap.json
      with_items: "{{ configmaps }}"
      when: item != None
      changed_when: False
      tags: [configmap, template]

    - name: apply configmaps
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-configmap.json
      with_items: "{{ configmaps }}"
      when: item != None and not ansible_check_mode
      tags: [configmap]

    # Secrets

    - name: secret template
      template: src={{secret_template}} dest={{dest_path}}/{{item.name}}-secret.json
      with_items: "{{ secrets }}"
      when: item != None
      changed_when: False
      no_log: True 
      tags: [secret, template]

    - name: apply secrets
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-secret.json
      with_items: "{{ secrets }}"
      when: item != None and not ansible_check_mode
      no_log: True 
      tags: [secret]

    # PodPresets

    - name: podpresets template
      template: src={{podpresets_template}} dest={{dest_path}}/{{item.name}}-podpresets.json
      with_items: "{{ podpresets }}"
      when: item != None
      changed_when: False
      no_log: True
      tags: [podpresets, template]

    - name: apply podpresets
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-podpresets.json
      with_items: "{{ podpresets }}"
      when: item != None and not ansible_check_mode
      no_log: False
      tags: [podpresets]

    # DaemonSets

    - name: daemonset template
      template: src={{daemonset_template}} dest={{dest_path}}/{{item.name}}-daemonset.json
      with_items: "{{ daemonsets }}"
      when: item != None
      changed_when: False
      tags: [daemonset, template]

    - name: apply daemonsets
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-daemonset.json
      with_items: "{{ daemonsets }}"
      when: item != None and not ansible_check_mode
      tags: [daemonset]

    - name: get daemonsets
      command: kubectl --server="{{kubernetes_master}}" get daemonsets -o json
      register: existing_daemonsets
      check_mode: no 
      changed_when: False
      tags: [daemonset, audit, delete]

    - block:
        - name: audit daemonsets
          debug: msg="daemonset {{ item }} was not defined"
          with_items: "{{ undefined_daemonsets }}"
          when: item != None
          tags: [daemonset, audit, delete]

        - name: delete undefined daemonsets
          command: kubectl --server="{{kubernetes_master}}" delete daemonset "{{ item }}"
          with_items: "{{ undefined_daemonsets }}"
          when: item != None and not ansible_check_mode
          tags: [daemonset, delete]
      vars:
        undefined_daemonsets: "{{ (existing_daemonsets.stdout|from_json)['items']|map(attribute='metadata.name')|difference(daemonsets|map(attribute='name'))|list }}"

    # Services

    - name: service template
      template: src={{service_template}} dest={{dest_path}}/{{item.name}}-service.json
      with_items: "{{ services }}"
      when: item != None
      changed_when: False
      tags: [service, template]

    - name: apply services
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-service.json
      with_items: "{{ services }}"
      when: item != None and not ansible_check_mode
      tags: [service]

    - name: get services
      command: kubectl --server="{{kubernetes_master}}" get services -l "component!=apiserver,canary!=true" -o json
      register: existing_services
      check_mode: no 
      changed_when: False
      tags: [service, audit, delete]

    - block:
      - name: audit services
        debug: msg="service {{ item }} was not defined"
        with_items: "{{ undefined_services }}"
        when: item != None
        tags: [service, audit, delete]

      - name: delete undefined services
        command: kubectl --server="{{kubernetes_master}}" delete service "{{ item }}"
        with_items: "{{ undefined_services }}"
        when: item != None and not ansible_check_mode
        tags: [service, delete]
      vars:
        undefined_services: "{{ (existing_services.stdout|from_json)['items']|map(attribute='metadata.name')|difference(services|map(attribute='name'))|list }}"

    # Canary Services

    - name: canary service template
      template: src={{service_canary_template}} dest={{dest_path}}/{{item.name}}-canary-service.json
      with_items: "{{ services|selectattr('canary', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [canary, service, template]

    - name: apply canary services
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-canary-service.json
      with_items: "{{ services|selectattr('canary', 'defined')|list }}"
      when: item != None and not ansible_check_mode
      tags: [canary, service]

    - name: get canary services
      command: kubectl --server="{{kubernetes_master}}" get services -l "component!=apiserver,canary==true" -o json
      register: existing_carnary_services
      check_mode: no
      changed_when: False
      tags: [canary, audit, delete]

    # Deployments

    - name: deployment template
      template: src={{deployment_template}} dest={{dest_path}}/{{item.name}}-deployment.json
      vars:
        service_name: "{{ item.name }}"
        pod: "{{ item.pod }}"
        canary: False
      with_items: "{{ services|selectattr('pod', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [deployment, template]

    - name: apply deployments
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-deployment.json
      with_items: "{{ services|selectattr('pod', 'defined')|list }}"
      when: item != None and not ansible_check_mode
      tags: [deployment]

    - name: get deployments
      command: kubectl --server="{{kubernetes_master}}" get deployments -l "canary!=true" -o json
      register: existing_deployments
      check_mode: no
      changed_when: False
      tags: [deployment, audit, delete]

    - block:
      - name: audit deployments
        debug: msg="deployment {{ item }} was not defined"
        with_items: "{{ undefined_deployments }}"
        when: item != None
        tags: [deployment, audit, delete]

      - name: delete undefined deployments
        command: kubectl --server="{{kubernetes_master}}" delete deployment "{{ item }}"
        with_items: "{{ undefined_deployments }}"
        when: item != None and not ansible_check_mode
        tags: [deployment, delete]
      vars:
        undefined_deployments: "{{ (existing_deployments.stdout|from_json)['items']|map(attribute='metadata.name')|difference(services|map(attribute='name'))|list }}"

    # Canary Deployments

    - name: canary deployment template
      template: src={{deployment_template}} dest={{dest_path}}/{{item.name}}-canary-deployment.json
      vars:
        service_name: "{{ item.name }}-canary"
        pod: "{{ item.canary }}"
        canary: True
      with_items: "{{ services|selectattr('canary', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [canary, deployment, template]

    - name: apply canary deployments
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-canary-deployment.json
      with_items: "{{ services|selectattr('canary', 'defined')|list }}"
      when: item != None and not ansible_check_mode
      tags: [canary, deployment]

    - name: get canary deployments
      command: kubectl --server="{{kubernetes_master}}" get deployments -l "canary==true" -o json
      register: existing_canary_deployments
      check_mode: no
      changed_when: False
      tags: [canary, deployment, audit, delete]

    # Network Policies

    - name: networkpolicy template
      template: src={{networkpolicy_template}} dest={{dest_path}}/{{item.name}}-networkpolicy.json
      with_items: "{{ services|selectattr('networkpolicy', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [networkpolicy, template]

    # Horizontal Pod Autoscaler

    - name: hpa template
      template: src={{hpa_template}} dest={{dest_path}}/{{item.name}}-hpa.json
      with_items: "{{ services|selectattr('autoscaler', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [hpa, template]

    - name: apply hpa
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-hpa.json
      with_items: "{{ services|selectattr('autoscaler', 'defined')|list }}"
      when: item != None and not ansible_check_mode
      tags: [hpa]

    - name: get hpa
      command: kubectl --server="{{kubernetes_master}}" get hpa -o json
      register: existing_hpa
      check_mode: no
      changed_when: False
      tags: [hpa, audit, delete]

    - block:
      - name: audit hpa
        debug: msg="hpa {{ item }} was not defined"
        with_items: "{{ undefined_hpa }}"
        when: item != None
        tags: [hpa, audit, delete]

      - name: delete undefined hpa
        command: kubectl --server="{{kubernetes_master}}" delete hpa "{{ item }}"
        with_items: "{{ undefined_hpa }}"
        when: item != None and not ansible_check_mode
        tags: [hpa, delete]
      vars:
        undefined_hpa: "{{ (existing_hpa.stdout|from_json)['items']|map(attribute='metadata.name')|difference(services|selectattr('autoscaler', 'defined')|map(attribute='name'))|list }}"

    # Endpoints

    - name: endpoints template
      template: src={{endpoints_template}} dest={{dest_path}}/{{item.name}}-endpoints.json
      with_items: "{{ services|selectattr('endpoints', 'defined')|list }}"
      when: item != None
      changed_when: False
      tags: [endpoint, template]

    - name: apply endpoints
      command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-endpoints.json
      with_items: "{{ services|selectattr('endpoints', 'defined')|list }}"
      when: item != None and not ansible_check_mode
      tags: [endpoint]
