- name: Kubernetes Playbook
  hosts: localhost
  connection: local
  gather_facts: False
  strategy: debug
  no_log: True
  vars:
    max_delete: 10
    dest_path: /dev/shm #todo
#    dest_path: /docker
    sidecars: []
    namespace: "{{namespaces[0]}}" #todo

  pre_tasks:
    - name: merge yaml files
      shell: 'yamlreader $(find {{inventory_dir}} -name "*.yml" -type f) > {{dest_path}}/services.yml'
      args:
        executable: /bin/bash
      when: namespaces is undefined
      tags: [always]

    - name: include vars
      include_vars:
        file: '{{dest_path}}/services.yml'
      when: namespaces is undefined
      tags: [always]

  roles:
    - namespace
    - networkpolicy
    - persistentvolume
    - persistentvolumeclaim
    - limits
    - configmap
#    - secret #todo
    - podpresets
    - daemonset
    - service
    - deployment
    - statefulset
    - hpa
#    - endpoints #todo

