---
# tasks file for configmap

- name: template
  template:
    src=templates/configmap.j2
    dest={{dest_path}}/{{item.name}}-configmap.json
  with_items: "{{ configmaps }}"
  when: item != None
  changed_when: False
  tags: [configmap, template]

- name: apply
  command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-configmap.json
  with_items: "{{ configmaps }}"
  when: item != None and not ansible_check_mode
  tags: [configmap]
