galaxy_info:
  author: your name
  description: your description
  company: your company (optional)

  license: license (GPLv2, CC-BY, etc)

  min_ansible_version: 1.2

  galaxy_tags: []

dependencies:
    - namespace
    - networkpolicy
    - persistentvolume
    - persistentvolumeclaim
    - limits
    - configmap
    - secret
    - serviceaccount
    - role
    - rolebinding
    - clusterrolebinding
##    - podpresets #todo
    - daemonset
    - service
    - deployment
    - statefulset
    - hpa
    - endpoints
