---
# defaults file for service

role_name: "{{role_path|basename}}"
resource_type: "{{role_name}}"
resources: "{{ namespace.services|selectattr('ports', 'defined')|list + namespace.services|selectattr('externalName', 'defined')|list }}"
