---
# defaults file for serviceaccount

role_name: "{{role_path|basename}}"
resource_type: "{{role_name}}"
resources: "{{ namespace.serviceAccounts|default([])|selectattr('clusterRoleBinding', 'defined')|list + namespace.services|default([])|selectattr('clusterRoleBinding', 'defined')|list + namespace.daemonsets|default([])|selectattr('clusterRoleBinding', 'defined')|list }}"
