---
# tasks file for podpreset

# PodPresets

- name: podpresets template
  template:
    src=templates/podpresets.j2
    dest={{dest_path}}/{{item.name}}-podpresets.json
  with_items: "{{ podpresets }}"
  when: item != None
  changed_when: False
  no_log: True
  tags: [podpresets, template]

- name: apply podpresets
  command: kubectl --server="{{kubernetes_master}}" apply -f {{dest_path}}/{{item.name}}-podpresets.json
  with_items: "{{ podpresets }}"
  when: item != None and not ansible_check_mode
  no_log: False
  tags: [podpresets]
