---
# defaults file for serviceaccount

role_name: "{{role_path|basename}}"
resource_type: "{{role_name}}"
resources: "{{ namespace.services|selectattr('roleBinding', 'defined')|list  + namespace.daemonsets|selectattr('roleBinding', 'defined')|list + namespace.services|selectattr('clusterRoleBinding', 'defined')|list  + namespace.daemonsets|selectattr('clusterRoleBinding', 'defined')|list }}"
